### ISSUE TITLE
The type TaskListener cannot be resolved.

### ISSUE THREAD

**Issue by eity0323** [SnowdreamFramework/android-downloader#7]
I use the jar in eclipse,but i get the error “The type com.github.snowdream.android.util.concurrent.TaskListener cannot be resolved. It is indirectly referenced from required .class files".how can i fix it?

**Comment by snowdream** [comment]
grab via Maven:

<dependency>
  <groupId>com.github.snowdream.android.app</groupId>
  <artifactId>downloader</artifactId>
  <version>1.0</version>
</dependency>
or Gradle:

    compile 'com.github.snowdream.android.app:downloader:1.0'
